[
  {
    "id": "DM-0001",
    "name": "Risidipalm impurity-1",
    "cas": "17412-23-6",
    "category": "Risidipalm",
    "formula": "C8H8ClN3",
    "mw": 181.62,
    "purity": "<95%",
    "grade": "in-house standard",
    "synonyms": "Imidazo[1,2-b]pyridazine, 6-chloro-2,8-dimethyl",
    "appearance": "yellow solid",
    "storage": "2-8°C",
    "application": "NA",
    "description": "yellow color solid",
    "availability": "In Stock",
    "image": "DM-0001.png"
  },
  {
    "id": "DM-0002",
    "name": "Risidipalm impurity-2 Regio-isomer",
    "cas": "17412-20-3",
    "category": "Risidipalm",
    "formula": "C8H8ClN3",
    "mw": 181.62,
    "purity": "<95%",
    "grade": "in-house standard",
    "synonyms": "6-Chloro-2,7-dimethylimidazo[1,2-b]pyridazine",
    "appearance": "yellow solid",
    "storage": "2-8°C",
    "application": "NA",
    "description": "yellow color solid",
    "availability": "In Stock",
    "image": "DM-0002.png"
  },
  {
    "id": "DM-0003",
    "name": "Abacavir N-nitroso",
    "cas": "NA",
    "category": "Abacavir",
    "formula": "C14H17N7O2",
    "mw": 315.3,
    "purity": "<98%",
    "grade": "in-house standard",
    "synonyms": "N-(2-amino-9-((1R,4S)-4-(hydroxymethyl)cyclopent-2-en-1-yl)-9H-purin-6-yl)-N-cyclopropylnitrous amide",
    "appearance": "Faint white to pale yellow solid",
    "storage": "2-8°C",
    "application": "NA",
    "description": "Faint white solid",
    "availability": "In Stock",
    "image": "DM-0003.png"
  },
  {
    "id": "DM-0004",
    "name": "Nilotinib N-nitroso",
    "cas": "2925306-68-7",
    "category": "Nilotinib",
    "formula": "C28H21F3N8O2",
    "mw": 558.5,
    "purity": "<98%",
    "grade": "in-house standard",
    "synonyms": "4-Methyl-N-(3-(4-methyl-1H-imidazol-1-yl)-5-(trifluoromethyl)phenyl)-3-(nitroso(4-(pyridin-3-yl)pyrimidin-2-yl)amino)benzamide",
    "appearance": "yellow to orange solid",
    "storage": "2-8°C",
    "application": "",
    "description": "yellow solid",
    "availability": "In Stock",
    "image": "DM-0004.png"
  },
  {
    "id": "DM-0005",
    "name": "Tenofovir impurity K",
    "cas": "4121-40-8",
    "category": "Tenofovir",
    "formula": "C8H9N5",
    "mw": 175.2,
    "purity": "<95%",
    "grade": "in-house standard",
    "synonyms": "9-Propenyladenine",
    "appearance": "white to off white solid",
    "storage": "2-8°C",
    "application": "",
    "description": "off white solid",
    "availability": "In Stock",
    "image": "DM-0005.png"
  },
  {
    "id": "DM-0006",
    "name": "(Z)-9-Propenyl adenine",
    "cas": "1464851-21-5",
    "category": "Tenofovir",
    "formula": "C8H9N6",
    "mw": 175.2,
    "purity": "<95%",
    "grade": "in-house standard",
    "synonyms": "(Z)-9-(prop-1-en-1-yl)-9H-purin-6-amine",
    "appearance": "white to off white solid",
    "storage": "2-8°C",
    "application": "",
    "description": "off white solid",
    "availability": "In Stock",
    "image": "DM-0006.png"
  }
]
